# Generated by Django 3.2.3 on 2022-09-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coleccion',
            fields=[
                ('idColec', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('idEnvio', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='documento',
            fields=[
                ('idDoc', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('tipoDocumento', models.CharField(max_length=50)),
                ('rutaDoc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='enviar',
            fields=[
                ('idEnvio', models.CharField(default='0000000', max_length=30, primary_key=True, serialize=False)),
                ('codigoUsuario', models.CharField(max_length=11)),
                ('idDoc', models.CharField(max_length=30)),
                ('destinatario', models.CharField(max_length=100)),
                ('emisario', models.CharField(max_length=100)),
                ('mensaje', models.TextField(max_length=1000)),
                ('etiqueta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='reporte',
            fields=[
                ('idReporte', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('idColec', models.CharField(max_length=30)),
                ('idEnvio', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('codigoUsuario', models.CharField(default='300000', max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correoUsu', models.EmailField(max_length=50)),
                ('contrasena', models.CharField(max_length=15)),
                ('programa', models.CharField(max_length=100)),
                ('programa2', models.CharField(default='Sin segundo programa', max_length=100)),
                ('rol', models.CharField(default='Seleccione su rol', max_length=13)),
            ],
        ),
    ]
