# Generated by Django 3.2.3 on 2022-10-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='superUser',
            fields=[
                ('correoUser', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombreUser', models.CharField(max_length=100)),
                ('contraUser', models.CharField(max_length=15)),
            ],
        ),
    ]
