# Generated by Django 3.2.3 on 2022-10-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigoUsuario',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='Estudiante', max_length=13),
        ),
    ]
