# Generated by Django 3.2.3 on 2022-10-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20221019_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coleccion',
        ),
        migrations.DeleteModel(
            name='documento',
        ),
        migrations.DeleteModel(
            name='enviar',
        ),
        migrations.DeleteModel(
            name='reporte',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='programa2',
        ),
    ]
